import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const OUTPUT_FILE = path.join(
  ROOT,
  "src/features/ai-agents/generatedProjectTree.ts"
);

const INCLUDED_ROOTS = ["src", "convex"];
const IGNORED_NAMES = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  ".turbo",
  ".vercel",
  ".convex",
  "_generated",
]);

const MAX_DEPTH = 6;

async function buildTree(dir, prefix = "", depth = 0) {
  if (depth > MAX_DEPTH) return [];

  const entries = await readdir(dir, { withFileTypes: true });
  const visibleEntries = entries
    .filter((entry) => !IGNORED_NAMES.has(entry.name))
    .filter((entry) => !entry.name.endsWith(".map"))
    .sort((a, b) => {
      if (a.isDirectory() && !b.isDirectory()) return -1;
      if (!a.isDirectory() && b.isDirectory()) return 1;
      return a.name.localeCompare(b.name);
    });

  const lines = [];

  for (const entry of visibleEntries) {
    const fullPath = path.join(dir, entry.name);
    const marker = entry.isDirectory() ? "📁" : "📄";
    lines.push(`${prefix}${marker} ${entry.name}`);

    if (entry.isDirectory()) {
      lines.push(...(await buildTree(fullPath, `${prefix}  `, depth + 1)));
    }
  }

  return lines;
}

const sections = [];

for (const rootName of INCLUDED_ROOTS) {
  const rootPath = path.join(ROOT, rootName);
  const lines = await buildTree(rootPath, "  ", 0);
  sections.push(`📁 ${rootName}\n${lines.join("\n")}`);
}

const generatedAt = new Date().toISOString();
const tree = sections.join("\n\n");

const content = `// This file is generated by scripts/generateProjectTree.mjs.\n// Do not edit manually.\n\nexport const generatedProjectTree = ${JSON.stringify(
  `Generated at: ${generatedAt}\n\n${tree}`,
  null,
  2
)};\n`;

await writeFile(OUTPUT_FILE, content, "utf8");
console.log(`Generated ${path.relative(ROOT, OUTPUT_FILE)}`);
